CREATE TABLE MEDICAL_DEVICE(
	ID SERIAL PRIMARY KEY, 
	NAME VARCHAR(40), 
	AREA VARCHAR(25));
CREATE TABLE SURGERY(
	ID SERIAL PRIMARY KEY, 
	NAME VARCHAR(40), 
	AREA VARCHAR(25), 
	LEVELS INTEGER);
CREATE TABLE FAMILY_DISEASE(
	ID SERIAL PRIMARY KEY, 
	NAME VARCHAR(40), 
	AREA VARCHAR(25));
CREATE TABLE LOGIN(
	NAME VARCHAR(25), 
	PASSWORD VARCHAR(25), 
	PRIMARY KEY(NAME,PASSWORD));
CREATE TABLE MEDICATION(
	ID SERIAL PRIMARY KEY, 
	NAME VARCHAR(25), 
	USAGES VARCHAR(25));
CREATE TABLE DISCOMFORT(
	ID SERIAL PRIMARY KEY, 
	NAME VARCHAR(25), 
	AREA VARCHAR(25), 
	LEVELS INTEGER);
CREATE TABLE BLOOD_TYPE(
	ID SERIAL PRIMARY KEY, 
	TYPES VARCHAR(2), 
	RH CHAR(1));
CREATE TABLE PATIENT(
	ID SERIAL PRIMARY KEY, 
	NAME VARCHAR(30), 
	AGE INTEGER, 
	WEIGHT FLOAT, 
	HEIGHT FLOAT, 
	MAJOR_DISCOMFORT INTEGER REFERENCES DISCOMFORT(ID)
		ON DELETE RESTRICT
		ON UPDATE CASCADE, 
	ALLERGY VARCHAR(20), 
	EXAMINATION_DATE DATE, 
	MEDICATIONS INTEGER REFERENCES MEDICATION(ID)
		ON DELETE RESTRICT
		ON UPDATE CASCADE, 
	FAMILY_DISEASES INTEGER REFERENCES FAMILY_DISEASE(ID)
		ON DELETE RESTRICT
		ON UPDATE CASCADE, 
	SURGERY INTEGER REFERENCES SURGERY(ID)
		ON DELETE RESTRICT
		ON UPDATE CASCADE, 
	MEDICAL_DEVICE INTEGER REFERENCES MEDICAL_DEVICE(ID)
		ON DELETE RESTRICT
		ON UPDATE CASCADE, 
	BLOOD_TYPE INTEGER REFERENCES BLOOD_TYPE(ID)
		ON DELETE RESTRICT
		ON UPDATE CASCADE)